apiVersion: v1
kind: List
metadata:
  name: watch-keeper-deployment
  annotations:
    version: "{{TRAVIS_COMMIT}}"
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: watch-keeper-sa
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
        razee/watch-resource: "true"
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    imagePullSecrets:
    - name: registry-default-secret

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: watch-keeper-rb
      labels:
        razee/force-apply: "true"
        addonmanager.kubernetes.io/mode: Reconcile
        razee/watch-resource: "true"
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: ServiceAccount
      name: watch-keeper-sa

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: watch-keeper-deny-ingress
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    spec:
      podSelector:
        matchLabels:
          app: watch-keeper
      policyTypes:
      - Ingress
      ingress: []

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        version: "{{TRAVIS_COMMIT}}"
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      name: watch-keeper
      labels:
        razee/restart-on-config-change: "true"
        addonmanager.kubernetes.io/mode: Reconcile
        razee/watch-resource: "true"
    spec:
      replicas: 1
      revisionHistoryLimit: 0
      selector:
        matchLabels:
          app: watch-keeper
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: watch-keeper
          name: watch-keeper
        spec:
          serviceAccountName: watch-keeper-sa
          containers:
          - env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: RAZEEDASH_URL
                valueFrom:
                  configMapKeyRef:
                    name: watch-keeper-config
                    key: RAZEEDASH_URL
              - name: RAZEEDASH_ORG_KEY
                valueFrom:
                  secretKeyRef:
                    name: watch-keeper-secret
                    key: RAZEEDASH_ORG_KEY
              - name: NODE_ENV
                value: "production"
            image: "quay.io/razee/watch-keeper:{{TRAVIS_COMMIT}}"
            imagePullPolicy: Always
            name: watch-keeper
            resources:
              limits:
                memory: 500Mi
                cpu: 400m
              requests:
                memory: 100Mi
                cpu: 50m
            livenessProbe:
              exec:
                command:
                - sh/liveness.sh
              initialDelaySeconds: 600
              periodSeconds: 300
              timeoutSeconds: 30
              failureThreshold: 1
